Repository 6ITAll/book-it-da, pull requests merged in 2024-12, with the labels that each got.

#16 :memo:docs: add PR template
  .github/pull_request_template.md
Labels: setting

#18 :construction_worker:chore: add eslint on pr ci workflow
  .github/workflows/eslint-on-pr.yml
Labels: setting

#21 ✨feat: 레이아웃 작성, 패키지 설치
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/main.tsx
  src/pages/MainPage/BookSearch.tsx
  src/pages/MainPage/Login.tsx
  src/pages/MainPage/Main.tsx
  src/pages/MainPage/Mypage.tsx
  src/pages/MainPage/page.css
Labels: setting

#26 Eslint 설정 오류
  eslint.config.js
  src/App.tsx
  src/features/counter/counterSlice.ts
  src/features/user/userSlice.ts
  src/main.tsx
  src/pages/MainPage/Login.tsx
  src/pages/MainPage/Main.tsx
  src/pages/NotFoundPage/NotFound.tsx
  src/routes/RoutePath.ts
  src/routes/index.tsx
  src/shared/types/type.ts
  src/store/index.tsx
  vite.config.ts
Labels: bug

#28 prettier 적용 범위 버그 픽스
  .github/ISSUE_TEMPLATE/bug-fix-template.md
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/pull_request_template.md
  .github/workflows/eslint-on-pr.yml
  .prettierrc
  .vscode/settings.json
  src/App.css
  src/pages/MainPage/page.css
  tsconfig.app.json
Labels: bug

#32 커밋 템플릿 타입 추가
  .gitmessage.txt
Labels: setting

#33 마이페이지 개발
  src/App.tsx
  src/components/MyPage/TabSection.tsx
  src/components/MyPage/UserInfoSection.tsx
  src/components/MyPage/UserInfoSummary.tsx
  src/pages/MainPage/Mypage.tsx
  src/pages/MyPage/MyPage.tsx
Labels: feature

#37 MUI 아이콘 추가
  package-lock.json
  package.json
Labels: setting

#38 모달 컴포넌트 구현
  src/components/commons/HybridDialog.tsx
  src/constants/.gitkeep
Labels: feature

#41 절대 경로 자동 완성 src 기준으로 되는 문제 해결
  tsconfig.app.json
Labels: setting

#36 책 검색 페이지 구현
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/components/BookSearchPage/BestBookCard.tsx
  src/components/BookSearchPage/BestBookCarousel.tsx
  src/components/BookSearchPage/BookSearchBar.tsx
  src/components/BookSearchPage/Pagination.tsx
  src/components/BookSearchPage/SearchBookCard.tsx
  src/components/BookSearchPage/SortSelector.tsx
  src/components/commons/Carousel.tsx
  src/components/commons/CommonBookCard.tsx
  src/features/BookSearchPage/Slice/bookSearchSlice.ts
  src/features/BookSearchPage/api/bestBookGetApi.ts
  src/features/BookSearchPage/api/bookSearchApi.ts
  src/pages/BookSearchPage/BookSearch.tsx
  src/pages/MainPage/BookSearch.tsx
  src/shared/config/aladinConfig.ts
  src/store/index.tsx
  vite.config.ts
Labels: feature

#44 피드 페이지 구현
  package-lock.json
  package.json
  src/assets/images/sample1.jpg
  src/assets/images/sample10.jpg
  src/assets/images/sample2.jpg
  src/assets/images/sample3.jpg
  src/assets/images/sample4.jpg
  src/assets/images/sample5.jpg
  src/assets/images/sample6.jpg
  src/assets/images/sample7.jpg
  src/assets/images/sample8.jpg
  src/assets/images/sample9.jpg
  src/components/FeedPage/FeedTypeFilter.tsx
  src/components/FeedPage/PostTypeFilter.tsx
  src/components/FeedPage/mockPosts.ts
  src/components/commons/PostCard.tsx
  src/components/commons/ScrollToTop.tsx
  src/pages/MainPage/Main.tsx
  src/shared/types/type.ts
Labels: feature

#49 Excepted identifier but found "import" 오류
  package-lock.json
  package.json
Labels: bug

#53 다이얼로그 외부 클릭 시 안 닫히는 문제 해결
  src/components/commons/HybridDialog.tsx
Labels: bug

#60 React Quill 대체
  package-lock.json
  package.json
Labels: bug

#45 팔로워 팔로잉 다이얼로그 구현
  src/App.tsx
  src/components/MyPage/FollowList.tsx
  src/components/MyPage/TabSection.tsx
  src/components/MyPage/UserInfoSection.tsx
  src/components/MyPage/UserInfoSummary.tsx
  src/pages/MyPage/MyPage.tsx
Labels: feature

#61 포스트 작성 기능 구현
  src/components/FeedPage/OneLineReviewDialog.tsx
  src/components/FeedPage/PostingDialog.tsx
  src/components/FeedPage/WriteDialog.tsx
  src/components/commons/BookSearchAutoComplete.tsx
  src/components/commons/HybridDialog.tsx
  src/components/commons/TextEditor.tsx
  src/pages/MainPage/Main.tsx
  src/shared/types/type.ts
Labels: feature

#67 한줄평 다이얼로그 별점 기능 추가
  src/components/FeedPage/OneLineReviewDialog.tsx
  src/components/commons/StarRating.tsx
  src/shared/types/type.ts
Labels: feature

#43 로그인&회원가입 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/LoginSignupPage/Login.tsx
  src/components/LoginSignupPage/Signup.tsx
  src/pages/LoginSignupPage/LoginPage.tsx
  src/pages/LoginSignupPage/SignupPage.tsx
  src/pages/MainPage/Login.tsx
Labels: feature

#66 테스트 환경 세팅
  .gitignore
  .storybook/main.ts
  .storybook/preview-head.html
  .storybook/preview.ts
  .storybook/test-runner.ts
  .storybook/vitest.setup.ts
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/styles/theme.ts
  vitest.workspace.ts
Labels: setting

#77 스토리북 시각적 테스트 추가
  chromatic.config.json
Labels: setting

#65 책 상세페이지 구현
  src/App.tsx
  src/components/BookDetailPage/ActionButtons.tsx
  src/components/BookDetailPage/AddToLibraryDialog.tsx
  src/components/BookDetailPage/BookDetailNavBar.tsx
  src/components/BookDetailPage/BookInfoBox.tsx
  src/components/BookDetailPage/BookIntroduceTab.tsx
  src/components/BookDetailPage/BookReviewTab.tsx
  src/components/BookDetailPage/FooterButtons.tsx
  src/components/BookDetailPage/GenderAgeChart.tsx
  src/components/BookDetailPage/GenderAgeSummary.tsx
  src/components/BookDetailPage/LeftBookDetailBox.tsx
  src/components/BookDetailPage/RightBookDetailBox.tsx
  src/components/BookSearchPage/BestBookCard.tsx
  src/components/BookSearchPage/BestBookCarousel.tsx
  src/components/BookSearchPage/SearchBookCard.tsx
  src/components/ReviewMorePage/ReviewSortOptions.tsx
  src/components/commons/DetailPagePostCard.tsx
  src/components/commons/DetailPageReviewCard.tsx
  src/components/commons/InfiniteScroll.tsx
  src/features/BookSearchPage/Slice/bookDetailSlice.ts
  src/features/BookSearchPage/api/bookDetailApi.ts
  src/pages/BookDetailPage/BookDetailPage.tsx
  src/pages/PostMorePage/PostMorePage.tsx
  src/pages/ReviewMorePage/ReviewMorePage.tsx
  src/shared/utils/navigation.ts
  src/store/index.tsx
Labels: feature

#90 제목 없는 공통 다이얼로그 구현
  src/components/FeedPage/WriteDialog.tsx
  src/components/commons/HybridDialog.tsx
  src/components/commons/NonTitleDialog.tsx
Labels: feature
