Repository 6ITAll/book-it-da, pull requests merged in 2025-01, with the labels that each got.

#80 스토리북 UI 테스트 자동화
  .github/workflows/storybook-tests.yml
  package-lock.json
  package.json
Labels: test

#85 피드페이지 UI 개선 및 리팩토링
  src/components/BookDetailPage/BookReviewTab.tsx
  src/components/FeedPage/FeedTypeFilter.tsx
  src/components/FeedPage/Filters/FeedTypeFilter.styles.ts
  src/components/FeedPage/Filters/FeedTypeFilter.tsx
  src/components/FeedPage/Filters/PostTypeFilter.styles.ts
  src/components/FeedPage/Filters/PostTypeFilter.tsx
  src/components/FeedPage/OneLineReviewDialog/OneLineReviewBookPreview.tsx
  src/components/FeedPage/OneLineReviewDialog/OneLineReviewDialog.styles.ts
  src/components/FeedPage/OneLineReviewDialog/OneLineReviewDialog.tsx
  src/components/FeedPage/OneLineReviewDialog/OneLineReviewTextField.tsx
  src/components/FeedPage/PostCard/PostCard.styles.ts
  src/components/FeedPage/PostCard/PostCard.tsx
  src/components/FeedPage/PostCard/PostCardContent.tsx
  src/components/FeedPage/PostCard/PostCardFooter.tsx
  src/components/FeedPage/PostCard/PostCardImage.tsx
  src/components/FeedPage/PostCard/PostHeader.tsx
  src/components/FeedPage/PostTypeFilter.tsx
  src/components/FeedPage/PostTypeSelectDialog/PostTypeButton.tsx
  src/components/FeedPage/PostTypeSelectDialog/PostTypeSelectDialog.styles.tsx
  src/components/FeedPage/PostTypeSelectDialog/PostTypeSelectDialog.tsx
  src/components/FeedPage/PostingDialog.tsx
  src/components/FeedPage/PostingDialog/BookSearchPopover.tsx
  src/components/FeedPage/PostingDialog/PostingBookPreview.tsx
  src/components/FeedPage/PostingDialog/PostingContent.tsx
  src/components/FeedPage/PostingDialog/PostingDialog.styles.ts
  src/components/FeedPage/PostingDialog/PostingDialog.tsx
  src/components/FeedPage/PostingDialog/PostingToolbar.tsx
  src/components/FeedPage/WriteDialog.tsx
  src/components/commons/BookSearchAutoComplete.tsx
  src/components/commons/PostCard.tsx
  src/components/commons/ScrollToTop.tsx
  src/components/commons/TextEditor.tsx
  src/constants/common.ts
  src/constants/dialog.ts
  src/constants/feedPage.ts
  src/constants/index.ts
  src/pages/MainPage/Main.tsx
  src/pages/ReviewMorePage/ReviewMorePage.tsx
  src/shared/types/type.ts
Labels: Design

#91 책장 페이지 구현
  src/components/BookShelvesPage/BookDetailDialog.tsx/BookDetailDialog.styles.ts
  src/components/BookShelvesPage/BookDetailDialog.tsx/BookDetailDialog.tsx
  src/components/BookShelvesPage/BookDetailDialog.tsx/BookReadingStatus.tsx
  src/components/BookShelvesPage/BookShelvesHeader.tsx
  src/components/BookShelvesPage/ShelvesBookcard/ShelvesBookCard.styles.ts
  src/components/BookShelvesPage/ShelvesBookcard/ShelvesBookCard.tsx
  src/components/BookShelvesPage/SortSelector.tsx
  src/components/BookShelvesPage/ViewToggle.tsx
  src/components/BookShelvesPage/sortBooks.ts
  src/features/BookShelvesPage/api/bookShelvesApi.ts
  src/features/BookShelvesPage/slice/bookShelvesSlice.ts
  src/features/BookShelvesPage/types/types.ts
  src/mocks/handlers/bookshelves.ts
  src/mocks/handlers/index.ts
  src/pages/BookShelvesPage/BookShelvesPage.tsx
  src/routes/RoutePath.ts
  src/routes/index.tsx
  src/shared/types/type.ts
  src/store/index.tsx
  src/utils/dateUtils.ts
Labels: feature

#69 포스팅 상세 페이지 구현
  src/App.css
  src/App.tsx
  src/components/PostDetailPage/OtherPostingCard.tsx
  src/components/PostDetailPage/OtherPostingGrid.tsx
  src/components/PostDetailPage/PostingContent.tsx
  src/components/PostDetailPage/PostingHeader.tsx
  src/components/PostDetailPage/PostingUserInfo.tsx
  src/components/commons/URLShareDialog.tsx
  src/features/PostDetailPage/api/postingApi.ts
  src/features/PostDetailPage/types/types.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/posting.ts
  src/pages/PostDetailPage/PostingDetailPage.tsx
  src/routes/RoutePath.ts
  src/routes/index.tsx
  src/shared/utils/formatCount.ts
  src/store/index.tsx
Labels: feature

#95 책 상세페이지에 포스팅 모달 공유 기능
  src/components/BookDetailPage/ActionButtons.tsx
  src/routes/RoutePath.ts
  src/routes/index.tsx
Labels: feature

#63 스낵바 구현
  index.html
  src/App.tsx
  src/components/Snackbar/SnackBar.tsx
  src/features/Snackbar/snackbarSlice.tsx
  src/store/store.tsx
Labels: feature

#94 피드 탭 구성
  src/components/BookDetailPage/BookReviewTab.tsx
  src/components/MyPage/Feed/Feed.tsx
  src/components/MyPage/Feed/LikedFeedTabPanel.tsx
  src/components/MyPage/Feed/PostFeedSection.tsx
  src/components/MyPage/Feed/ReviewFeedSection.tsx
  src/components/MyPage/Feed/UserFeedTabPanel.tsx
  src/components/MyPage/Library/LibraryTabPanel.tsx
  src/components/MyPage/TabSection.tsx
  src/features/MyPage/api/libraryApi.ts
  src/features/MyPage/api/userFeedsApi.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/user.ts
  src/pages/MyPage/MyPage.tsx
  src/shared/types/type.ts
  src/store/index.tsx
  tsconfig.app.json
Labels: feature

#99 상세페이지 api 설계
  package-lock.json
  src/components/BookDetailPage/AddToLibraryDialog.tsx
  src/components/BookDetailPage/BookDetailNavBar.tsx
  src/components/BookDetailPage/BookIntroduceTab.tsx
  src/components/BookDetailPage/BookReviewTab.tsx
  src/components/BookDetailPage/FooterButtons.tsx
  src/components/BookDetailPage/GenderAgeChart.tsx
  src/components/BookDetailPage/GenderAgeSummary.tsx
  src/components/BookDetailPage/RightBookDetailBox.tsx
  src/components/commons/DetailPagePostCard.tsx
  src/features/BookDetailPage/api/AddToLibraryApi.ts
  src/features/BookDetailPage/api/bookUserShelfCountApi.ts
  src/features/BookDetailPage/api/genderAgeApi.ts
  src/features/BookDetailPage/api/postApi.ts
  src/features/BookDetailPage/api/reviewApi.ts
  src/mocks/handlers/DetailPagePost.ts
  src/mocks/handlers/DetailPageReview.ts
  src/mocks/handlers/addToLibrary.ts
  src/mocks/handlers/genderAge.ts
  src/mocks/handlers/index.ts
  src/pages/BookDetailPage/BookDetailPage.tsx
  src/pages/PostMorePage/PostMorePage.tsx
  src/pages/ReviewMorePage/ReviewMorePage.tsx
  src/shared/types/type.ts
  src/store/index.tsx
Labels: feature

#114 헤더 검색바 기능 구현
  src/components/Header/Header.tsx
  src/pages/BookSearchPage/BookSearch.tsx
Labels: feature

#98 hybrid dialog 테스트 코드 작성
  src/components/BookShelvesPage/BookDetailDialog.tsx/BookDetailDialog.tsx
  src/components/FeedPage/OneLineReviewDialog/OneLineReviewDialog.tsx
  src/components/FeedPage/PostingDialog/PostingDialog.tsx
  src/components/MyPage/UserInfoSummary.tsx
  src/components/commons/HybridDialog/HybridDialog.stories.tsx
  src/components/commons/HybridDialog/HybridDialog.tsx
  src/components/commons/NonTitleDialog.tsx
Labels: test

#100 MUI Theme 커스텀
  src/App.tsx
  src/styles/theme.ts
Labels: setting, Design

#119 검색페이지 디자인/반응형 변경
  src/components/BookSearchPage/BestBookCard.tsx
  src/components/BookSearchPage/BestBookCarousel.tsx
  src/components/commons/Carousel.tsx
  src/pages/BookDetailPage/BookDetailPage.tsx
  src/pages/BookSearchPage/BookSearch.tsx
Labels: Design

#127 책 상세페이지&검색페이지 리펙토링
  src/components/BookDetailPage/ActionButtons.tsx
  src/components/BookDetailPage/AddToLibraryDialog.tsx
  src/components/BookDetailPage/BookDetail.styles.ts
  src/components/BookDetailPage/BookDetailContent.tsx
  src/components/BookDetailPage/BookDetailNavBar.tsx
  src/components/BookDetailPage/BookDetailSection.tsx
  src/components/BookDetailPage/BookInfoBox.tsx
  src/components/BookDetailPage/BookIntroduceTab.tsx
  src/components/BookDetailPage/BookReviewTab.tsx
  src/components/BookDetailPage/FooterButtons.tsx
  src/components/BookDetailPage/GenderAgeChart.tsx
  src/components/BookDetailPage/GenderAgeSummary.tsx
  src/components/BookDetailPage/LeftBookDetailBox.tsx
  src/components/BookDetailPage/RightBookDetailBox.tsx
  src/components/BookDetailPage/types.ts
  src/components/BookSearchPage/BestBookCard.tsx
  src/components/BookSearchPage/BestSellerSection.tsx
  src/components/BookSearchPage/BookSearch.style.ts
  src/components/BookSearchPage/BookSearchBar.tsx
  src/components/BookSearchPage/SearchBookCard.tsx
  src/components/BookSearchPage/SearchResult.tsx
  src/components/BookSearchPage/useSearchInput.ts
  src/components/commons/CommonBookCard.tsx
  src/features/BookDetailPage/api/AddToLibraryApi.ts
  src/features/BookDetailPage/api/postApi.ts
  src/features/BookDetailPage/api/reviewApi.ts
  src/features/BookDetailPage/types/types.ts
  src/features/BookSearchPage/api/bestBookGetApi.ts
  src/features/BookSearchPage/api/bookDetailApi.ts
  src/features/BookSearchPage/api/bookSearchApi.ts
  src/features/BookSearchPage/types/types.ts
  src/mocks/handlers/addToLibrary.ts
  src/pages/BookDetailPage/BookDetailPage.tsx
  src/pages/BookSearchPage/BookSearch.tsx
Labels: refactor

#137 책장 페이지 누락 기능 구현 및 리팩토링
  src/components/BookShelvesPage/BookDetailDialog/BookDetailDialog.styles.ts
  src/components/BookShelvesPage/BookDetailDialog/BookDetailDialog.tsx
  src/components/BookShelvesPage/BookDetailDialog/BookReadingStatus.tsx
  src/components/BookShelvesPage/BookShelves.styles.ts
  src/components/BookShelvesPage/BookShelvesHeader.tsx
  src/components/BookShelvesPage/ShelvesBookcard/ShelvesBookCard.styles.ts
  src/components/BookShelvesPage/ShelvesBookcard/ShelvesBookCard.tsx
  src/components/BookShelvesPage/SortSelector.tsx
  src/components/BookShelvesPage/ViewToggle.tsx
  src/components/BookShelvesPage/types.ts
  src/components/commons/URLShareDialog.tsx
  src/mocks/handlers/bookshelves.ts
  src/pages/BookShelvesPage/BookShelvesPage.tsx
  src/shared/types/type.ts
  src/shared/utils/dateUtils.ts
  src/utils/BookShelvesPage/readingStatusUtils.tsx
  src/utils/BookShelvesPage/sortBooks.tsx
  tsconfig.app.json
Labels: feature, refactor

#144 책검색,책상세페이지 관련 컴포넌트들 절대경로 수정
  src/components/BookDetailPage/ActionButtons.tsx
  src/components/BookDetailPage/AddToLibraryDialog.tsx
  src/components/BookDetailPage/BookDetailContent.tsx
  src/components/BookDetailPage/BookDetailNavBar.tsx
  src/components/BookDetailPage/BookDetailSection.tsx
  src/components/BookDetailPage/BookInfoBox.tsx
  src/components/BookDetailPage/BookIntroduceTab.tsx
  src/components/BookDetailPage/FooterButtons.tsx
  src/components/BookDetailPage/LeftBookDetailBox.tsx
  src/components/BookDetailPage/RightBookDetailBox.tsx
  src/components/BookSearchPage/BestSellerSection.tsx
  src/components/BookSearchPage/BookSearchBar.tsx
  src/components/BookSearchPage/SearchResult.tsx
Labels: refactor

#125 회원가입 스낵바 추가 & 회원가입 리팩토링
  src/components/LoginSignupPage/Signup/Signup.styles.ts
  src/components/LoginSignupPage/Signup/Signup.tsx
  src/features/SignupPage/type.ts
  src/pages/LoginSignupPage/SignupPage.tsx
Labels: feature, refactor

#133 포스팅 상세페이지 누락 기능 구현 및 리팩토링
  src/components/PostingDetailPage/OtherPostingCard.tsx
  src/components/PostingDetailPage/OtherPostingGrid.tsx
  src/components/PostingDetailPage/PostingContent.tsx
  src/components/PostingDetailPage/PostingDetail.styles.ts
  src/components/PostingDetailPage/PostingHeader.tsx
  src/components/PostingDetailPage/PostingUserInfo.tsx
  src/components/PostingWritePage/PostingWrite.tsx
  src/components/PostingWritePage/PostingWriteHeader.tsx
  src/components/commons/HybridDialog/HybridDialog.tsx
  src/features/PostDetailPage/api/postingApi.ts
  src/features/PostingWritePage/api/postingWriteApi.ts
  src/features/PostingWritePage/types/types.ts
  src/mocks/handlers/feed.ts
  src/mocks/handlers/posting.ts
  src/pages/PostingDetailPage/PostingDetailPage.tsx
  src/routes/RoutePath.ts
  src/routes/index.tsx
Labels: feature, refactor

#130 포스팅 저장 기능 구현 및 리팩토링
  package-lock.json
  package.json
  src/components/FeedPage/PostCard/PostCard.styles.ts
  src/components/FeedPage/PostCard/PostCard.tsx
  src/components/FeedPage/PostCard/PostCardHeader.tsx
  src/components/PostingWritePage/BookSearchPopover.tsx
  src/components/PostingWritePage/PostingBookPreview.tsx
  src/components/PostingWritePage/PostingContent.tsx
  src/components/PostingWritePage/PostingToolbar.tsx
  src/components/PostingWritePage/PostingWrite.styles.ts
  src/components/PostingWritePage/PostingWrite.tsx
  src/components/PostingWritePage/PostingWriteHeader.tsx
  src/components/PostingWritePage/types.ts
  src/components/commons/TextEditor.tsx
  src/constants/postingWrite.ts
  src/features/PostingWritePage/api/postingWriteApi.ts
  src/features/PostingWritePage/types/types.ts
  src/hooks/useTempSave.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/savePosting.ts
  src/pages/MainPage/Main.tsx
  src/pages/PostingWritePage/PostingWritePage.tsx
  src/shared/utils/navigation.ts
  tsconfig.app.json
Labels: feature, refactor

#145 마이페이지 누락 기능 구현
  src/components/MyPage/FollowList.tsx
  src/components/MyPage/Library/BookshelfCard.tsx
  src/components/MyPage/Library/LibraryTabPanel.tsx
  src/components/MyPage/UserInfoSection.tsx
  src/components/MyPage/UserInfoSummary.tsx
  src/features/MyPage/api/followApi.ts
  src/features/SNSLogin/Slice/kakaoSlice.ts
  src/features/SNSLogin/api/Kakaoapi.ts
  src/features/SNSLogin/auth/KakaoCallback.tsx
  src/features/user/types.ts
  src/features/user/userSlice.ts
  src/mocks/handlers/follow.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/kakao.ts
  src/pages/MyPage/MyPage.tsx
  src/routes/index.tsx
  src/shared/types/type.ts
  src/store/index.tsx
Labels: feature

#129 로그인-회원가입 페이지, 헤더 리팩토링
  src/components/Header/Header.styles.ts
  src/components/Header/Header.tsx
  src/components/Header/types.ts
  src/components/LoginSignupPage/Login/Login.styles.ts
  src/components/LoginSignupPage/Login/Login.tsx
  src/components/LoginSignupPage/Login/types.ts
  src/pages/LoginSignupPage/LoginPage.tsx
Labels: refactor

#146 아바타 유저페이지 이동기능 구현
  src/components/BookDetailPage/BookReviewTab.tsx
  src/components/FeedPage/PostCard/PostCardHeader.tsx
  src/components/MyPage/Feed/PostFeedSection.tsx
  src/components/MyPage/Feed/ReviewFeedSection.tsx
  src/components/PostMorePage/PostMoreTemplate.tsx
  src/components/PostingDetailPage/OtherPostingCard.tsx
  src/components/ReviewMorePage/ReviewMorePageTemplate.tsx
  src/components/commons/PostCard.tsx
  src/components/commons/ReviewCard.tsx
  src/features/BookDetailPage/types/types.ts
  src/mocks/handlers/DetailPagePost.ts
  src/mocks/handlers/DetailPageReview.ts
  src/shared/types/type.ts
  src/shared/utils/navigation.ts
Labels: feature

#141 하이브리드 다이어로그 aria버그 수정 & 책 서재 다이어로그 리팩토링
  src/components/BookDetailPage/AddToLibraryDialog.tsx
  src/components/BookDetailPage/FooterButtons.tsx
  src/components/Header/Header.tsx
  src/components/commons/HybridDialog/HybridDialog.tsx
  src/features/BookDetailPage/api/AddToLibraryApi.ts
Labels: bug, refactor

#158 배포 전 빌드 오류 해결
  src/App.tsx
  src/components/BookShelvesPage/BookDetailDialog/BookDetailDialog.tsx
  src/components/LoginSignupPage/Login.tsx
  src/components/LoginSignupPage/Login/Login.tsx
  src/components/LoginSignupPage/Signup/Signup.tsx
  src/components/MyPage/Feed/Feed.tsx
  src/components/MyPage/Feed/PostFeedSection.tsx
  src/components/MyPage/Feed/ReviewFeedSection.tsx
  src/components/PostMorePage/PostMoreTemplate.tsx
  src/components/PostingDetailPage/OtherPostingCard.tsx
  src/components/PostingDetailPage/OtherPostingGrid.tsx
  src/components/PostingDetailPage/PostingContent.tsx
  src/components/PostingDetailPage/PostingHeader.tsx
  src/components/PostingWritePage/PostingToolbar.tsx
  src/components/PostingWritePage/PostingWrite.tsx
  src/components/PostingWritePage/PostingWriteHeader.tsx
  src/components/commons/BookSearchAutoComplete.tsx
  src/components/commons/SnackBar.tsx
  src/features/BookShelvesPage/slice/bookShelvesSlice.ts
  src/features/BookShelvesPage/types/types.ts
  src/features/MyPage/api/userFeedsApi.ts
  src/features/PostingWritePage/types/types.ts
  src/features/SignupPage/types.ts
  src/features/user/types.ts
  src/hooks/useTempSave.ts
  src/pages/LikedPostMorePage/LikedPostMorePage.tsx
  src/pages/LikedReviewMorePage/LikedReviewMorePage.tsx
  src/pages/LoginSignupPage/LoginPage.tsx
  src/shared/types/type.ts
  src/utils/SignupPage/yupSchema.ts
Labels: bug

#161 기능 오류 수정
  src/components/PostingWritePage/PostingWrite.tsx
  src/components/commons/URLShareDialog.tsx
  src/hooks/useTempSave.ts
Labels: bug, feature

#162 리드미 작성
  README.md
Labels: documentation

#165 포스팅 작성 임시저장 로드 다이얼로그 표시 이슈 해결
  src/components/PostingWritePage/PostingWrite.styles.ts
  src/components/PostingWritePage/PostingWrite.tsx
  src/hooks/useTempSave.ts
Labels: bug, feature

#171 게시물 더보기 무한스크롤 이슈 해결
  src/pages/LikedPostMorePage/LikedPostMorePage.tsx
  src/pages/LikedReviewMorePage/LikedReviewMorePage.tsx
Labels: bug, feature

#172 mui 다크모드 적용
  src/App.css
  src/App.tsx
  src/components/BookDetailPage/ActionButtons.tsx
  src/components/BookDetailPage/BookDetail.styles.ts
  src/components/BookDetailPage/BookIntroduceTab.tsx
  src/components/BookDetailPage/BookReviewTab.tsx
  src/components/BookSearchPage/BestBookCarousel.tsx
  src/components/BookSearchPage/BookSearch.style.ts
  src/components/BookSearchPage/SearchResult.tsx
  src/components/BookShelvesPage/BookDetailDialog/BookDetailDialog.styles.ts
  src/components/BookShelvesPage/BookDetailDialog/BookDetailDialog.tsx
  src/components/BookShelvesPage/BookShelves.styles.ts
  src/components/BookShelvesPage/ShelvesBookcard/ShelvesBookCard.styles.ts
  src/components/BookShelvesPage/ShelvesBookcard/ShelvesBookCard.tsx
  src/components/DarkModeButton/DarkModeButton.tsx
  src/components/FeedPage/Filters/PostTypeFilter.styles.ts
  src/components/FeedPage/Filters/PostTypeFilter.tsx
  src/components/FeedPage/PostCard/PostCard.styles.ts
  src/components/FeedPage/PostCard/PostCardContent.tsx
  src/components/FeedPage/PostCard/PostCardFooter.tsx
  src/components/FeedPage/PostTypeSelectDialog/PostTypeSelectDialog.styles.tsx
  src/components/Header/Header.tsx
  src/components/LoginSignupPage/Login/Login.tsx
  src/components/LoginSignupPage/Signup/Signup.tsx
  src/components/MyPage/Feed/PostFeedSection.tsx
  src/components/MyPage/Feed/ReviewFeedSection.tsx
  src/components/MyPage/UserInfoSummary.tsx
  src/components/MyPage/mypage.style.ts
  src/components/PostingDetailPage/PostingDetail.styles.ts
  src/components/PostingDetailPage/PostingUserInfo.tsx
  src/components/PostingWritePage/PostingWrite.styles.ts
  src/components/ReviewMorePage/ReviewMorePageTemplate.tsx
  src/components/commons/PostCard.tsx
  src/components/commons/ReviewCard.tsx
  src/components/commons/URLShareDialog.tsx
  src/features/DarkMode/darkModeSlice.ts
  src/store/index.tsx
  src/styles/theme.ts
Labels: Design

#159 api 문서화 및 정리
  docs/CNAME
  docs/favicon-16x16.png
  docs/favicon-32x32.png
  docs/index.css
  docs/index.html
  docs/oauth2-redirect.html
  docs/swagger-initializer.js
  docs/swagger-ui-bundle.js
  docs/swagger-ui-bundle.js.map
  docs/swagger-ui-es-bundle-core.js
  docs/swagger-ui-es-bundle-core.js.map
  docs/swagger-ui-es-bundle.js
  docs/swagger-ui-es-bundle.js.map
  docs/swagger-ui-standalone-preset.js
  docs/swagger-ui-standalone-preset.js.map
  docs/swagger-ui.css
  docs/swagger-ui.css.map
  docs/swagger-ui.js
  docs/swagger-ui.js.map
  docs/swagger.yaml
  package-lock.json
  package.json
  src/components/FeedPage/PostCard/PostCard.tsx
  src/components/FeedPage/PostCard/PostCardFooter.tsx
  src/components/FeedPage/PostCard/PostCardHeader.tsx
  src/components/LoginSignupPage/Login/Login.tsx
  src/components/LoginSignupPage/Signup/Signup.tsx
  src/components/PostingDetailPage/PostingHeader.tsx
  src/components/PostingDetailPage/PostingUserInfo.tsx
  src/features/BookDetailPage/api/AddToLibraryApi.ts
  src/features/BookShelvesPage/slice/bookShelvesSlice.ts
  src/features/DarkMode/darkModeSlice.ts
  src/features/FeedPage/api/feedApi.ts
  src/features/FeedPage/slice/feedSlice.ts
  src/features/FeedPage/types/types.ts
  src/features/MyPage/api/followApi.ts
  src/features/PostDetailPage/api/postingApi.ts
  src/features/PostDetailPage/slice/postingDetailSlice.ts
  src/features/SNSLogin/auth/KakaoCallback.tsx
  src/features/SignupPage/types.ts
  src/features/commons/followApi.ts
  src/features/commons/likeApi.ts
  src/features/commons/types.ts
  src/features/user/userSlice.ts
  src/mocks/handlers/posting.ts
  src/pages/BookShelvesPage/BookShelvesPage.tsx
  src/pages/MainPage/Main.tsx
  src/pages/PostingDetailPage/PostingDetailPage.tsx
  src/shared/utils/formatCount.ts
  src/store/index.tsx
  src/utils/SignupPage/yupSchema.ts
  src/utils/supabaseClient.ts
  swagger-server.js
  swagger.js
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts
Labels: documentation, feature, refactor

#182 로그인 회원가입 supabase 연동
  src/App.tsx
  src/assets/images/kakao-logo.svg
  src/assets/images/kakao_login.png
  src/components/Header/Header.tsx
  src/components/Header/userMenu.tsx
  src/components/LoginSignupPage/Login/Login.styles.ts
  src/components/LoginSignupPage/Login/Login.tsx
  src/components/LoginSignupPage/Signup/Signup.styles.ts
  src/components/LoginSignupPage/Signup/Signup.tsx
  src/features/SNSLogin/Slice/kakaoSlice.ts
  src/features/SNSLogin/auth/KakaoCallback.tsx
  src/features/user/userSlice.ts
  src/hooks/useAuthStateChange.ts
  src/hooks/useKakaoAuth.ts
  src/hooks/useKakaoSDK.ts
  src/hooks/usePerformAutoLogin.ts
  src/hooks/useRemeberMe.ts
  src/hooks/useSetAutoLogin.ts
  src/store/index.tsx
  src/store/userSlice/userSlice.tsx
  src/utils/SignupPage/checkDuplicate.ts
  src/utils/supabaseClient.ts
Labels: feature

#183 스켈레톤 작업
  src/components/BookDetailPage/BookDetailContent.tsx
  src/components/BookDetailPage/BookDetailSection.tsx
  src/components/BookDetailPage/BookIntroduceTab.tsx
  src/components/BookDetailPage/LeftBookDetailBox.tsx
  src/components/BookDetailPage/RightBookDetailBox.tsx
  src/components/BookSearchPage/BestBookCard.tsx
  src/components/BookSearchPage/BestBookCarousel.tsx
  src/components/BookSearchPage/BookSearch.style.ts
  src/components/BookSearchPage/BookSearchSkeleton.tsx
  src/components/BookSearchPage/SearchResult.tsx
  src/components/BookSearchPage/useSearchInput.ts
  src/pages/BookDetailPage/BookDetailPage.tsx
Labels: Design

#195 빌드 오류 수정
  src/mocks/handlers/feed.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/posting.ts
  src/mocks/handlers/savePosting.ts
Labels: bug

#200 추가 정보 입력 페이지 & 정보 수정 페이지
  src/components/AdditionalInfo/AdditionalInfo.tsx
  src/components/LoginSignupPage/Login/Login.tsx
  src/components/LoginSignupPage/Signup/Signup.tsx
  src/features/SNSLogin/auth/KakaoCallback.tsx
  src/features/user/additionalInfoApi.ts
  src/features/user/userApi.ts
  src/features/user/userSlice.ts
  src/hooks/useAuthStateChange.ts
  src/hooks/usePerformAutoLogin.ts
  src/hooks/useSetAutoLogin.ts
  src/pages/EditAccountPage.tsx/EditAccountPage.tsx
  src/pages/PasswordChkPage/PasswordChkPage.tsx
  src/routes/index.tsx
  src/shared/types/type.ts
  src/store/index.tsx
  src/utils/SignupPage/yupSchema.ts
  src/utils/deleteUserFiles.ts
Labels: feature

#204 포스팅 댓글 기능 구현
  src/components/PostingDetailPage/CommentSection.tsx
  src/components/PostingDetailPage/PostingDetail.styles.ts
  src/pages/PostingDetailPage/PostingDetailPage.tsx
Labels: feature, Design
