Repository 6ITAll/book-it-da, pull requests merged in 2025-02, with the labels that each got.

#206 포스팅 상세 페이지 영어 내용 줄바꿈 이슈
  src/components/PostingDetailPage/PostingContent.tsx
Labels: bug

#214 깃헙 액션 스토리북 서버 실행 캐싱 문제로 인한 실패 해결
  .github/workflows/storybook-tests.yml
Labels: bug

#213 Deprecated된 artifact actions로 인한 버그 픽스
  .github/workflows/storybook-tests.yml
Labels: bug

#217 로그인 상태 관련 버그 해결
  src/components/BookDetailPage/FooterButtons.tsx
  src/components/FeedPage/PostCard/PostCardFooter.tsx
  src/features/SNSLogin/auth/KakaoCallback.tsx
Labels: bug

#221 Not found page 구현
  src/components/NotFoundPage/NotFoundContent.style.ts
  src/components/NotFoundPage/NotFoundContent.tsx
  src/pages/NotFoundPage/NotFound.tsx
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/routes/index.tsx
Labels: feature

#226 팔로우 리스트에 팔로우 버튼 미표시 버그 해결
  src/components/MyPage/FollowList.tsx
Labels: bug

#223 다른 사용자의 마이페이지에 팔로우/언팔로우 버튼 구현
  src/components/MyPage/FollowButton.tsx
  src/components/MyPage/UserInfoSection.tsx
  src/pages/MyPage/MyPage.tsx
Labels: feature

#191 렌더링 최적화
  src/components/BookDetailPage/AddToLibraryDialog.tsx
  src/components/BookDetailPage/BookshelfCreate.tsx
  src/components/BookDetailPage/getUserId.ts
  src/components/BookSearchPage/BookSearch.style.ts
  src/components/BookSearchPage/BookSearchBar.tsx
  src/components/BookSearchPage/SearchResult.tsx
  src/components/BookSearchPage/ViewOptionSelector.tsx
  src/components/BookSearchPage/useSearchInput.ts
  src/components/FeedPage/OneLineReviewDialog/OneLineReviewDialog.tsx
  src/components/FeedPage/OneLineReviewDialog/OneLineReviewTextField.tsx
  src/components/FeedPage/PostTypeSelectDialog/PostTypeSelectDialog.tsx
  src/components/FeedPage/WriteButton.tsx
  src/components/Header/Header.tsx
  src/components/commons/BookSearchAutoComplete.tsx
  src/components/commons/Carousel.tsx
  src/components/commons/StarRating.tsx
  src/features/BookSearchPage/api/bookSearchApi.ts
  src/features/BookSearchPage/types/types.ts
  src/features/DarkMode/darkModeSlice.ts
  src/pages/BookSearchPage/BookSearch.tsx
  src/pages/MainPage/Main.tsx
Labels: refactor

#247 피드 페이지 cls 개선
  package-lock.json
  package.json
  src/components/FeedPage/PostCard/PostCard.styles.ts
  src/components/FeedPage/PostCard/PostCard.tsx
  src/components/FeedPage/PostCard/PostCardSkeleton.tsx
  src/hooks/useColumnCount.ts
  src/pages/MainPage/Main.tsx
Labels: perfomance

#229 마이페이지 URL 업데이트 및 팔로우 버튼 수정
  src/components/MyPage/FollowButton.tsx
  src/features/user/userSlice.ts
  src/pages/EditAccountPage.tsx/EditAccountPage.tsx
  src/pages/MyPage/MyPage.tsx
Labels: bug, Design

#233 마이페이지 UI 수정
  src/components/MyPage/Feed/OneLineReviewSection.tsx
  src/components/MyPage/Feed/PostingSection.tsx
  src/components/MyPage/Library/BookshelfCard.tsx
Labels: Design

#230 포스팅 댓글 구현
  src/App.css
  src/components/PostingDetailPage/Comment/CommentInput.tsx
  src/components/PostingDetailPage/Comment/CommentItem.tsx
  src/components/PostingDetailPage/Comment/CommentReplies.tsx
  src/components/PostingDetailPage/Comment/CommentSection.tsx
  src/components/PostingDetailPage/Comment/LoadMoreRepliesButton.tsx
  src/components/PostingDetailPage/Comment/TagComment.tsx
  src/components/PostingDetailPage/Comment/TempNewReply.tsx
  src/components/PostingDetailPage/Comment/types.ts
  src/components/PostingDetailPage/CommentSection.tsx
  src/components/PostingDetailPage/OtherPostingGrid.tsx
  src/components/PostingDetailPage/PostingContent.tsx
  src/components/PostingDetailPage/PostingDetail.styles.ts
  src/components/commons/InfiniteScroll.tsx
  src/constants/comment.ts
  src/features/PostDetailPage/api/commentApi.ts
  src/features/PostDetailPage/slice/commentSlice.ts
  src/features/PostDetailPage/types/types.ts
  src/features/user/avatarUrlApi.ts
  src/features/user/userSlice.ts
  src/pages/PostingDetailPage/PostingDetailPage.tsx
  src/store/index.tsx
Labels: feature

#250 포스팅 상세 페이지 레이아웃 깨짐 현상 해결
  src/components/PostingDetailPage/PostingDetail.styles.ts
  src/pages/PostingDetailPage/PostingDetailPage.tsx
Labels: bug

#244 redux index 파일 분리
  package-lock.json
  public/mockServiceWorker.js
  src/main.tsx
  src/pages/MainPage/Main.tsx
  src/store/api/baseApi.ts
  src/store/api/bookApi.ts
  src/store/api/commentApi.ts
  src/store/api/feedApi.ts
  src/store/api/libraryApi.ts
  src/store/api/mypageApi.ts
  src/store/api/postingApi.ts
  src/store/api/reviewApi.ts
  src/store/api/userApi.ts
  src/store/index.ts
  src/store/index.tsx
  src/store/middleware.ts
  src/store/slices/bookSlice.ts
  src/store/slices/commentSlice.ts
  src/store/slices/feedSlice.ts
  src/store/slices/librarySlice.ts
  src/store/slices/uiSlice.ts
  src/store/slices/userSlice.ts
  src/utils/supabaseClient.ts
Labels: refactor

#257 msw 잔류 코드 삭제
  .depcheckrc
  .storybook/main.ts
  tsconfig.app.json
Labels: refactor

#252 피드페이지 좋아요 버튼 로직 수정
  src/components/FeedPage/PostCard/PostCardFooter.tsx
Labels: feature

#234 피드페이지 팔로우 팔로잉 UI수정
  src/components/FeedPage/PostCard/PostCardHeader.tsx
  src/components/MyPage/Feed/Feed.tsx
  src/components/MyPage/Feed/OneLineReviewSection.tsx
  src/components/commons/PostCard.tsx
  src/components/commons/ReviewCard.tsx
Labels: feature, Design

#259 책 상세페이지 리뷰 탭 오류 수정
  src/components/BookDetailPage/BookFeedTab.tsx
  src/components/BookDetailPage/BookMyReview.tsx
  src/features/BookDetailPage/api/bookOwnReviewApi.ts
Labels: bug

#261 userSlice loginSuccess parameter 오류
  src/hooks/usePerformAutoLogin.ts
  src/hooks/useSetAutoLogin.ts
Labels: bug

#265 naviagator & routes 리팩토링
  src/components/AdditionalInfo/AdditionalInfo.tsx
  src/components/BookDetailPage/ActionButtons.tsx
  src/components/BookDetailPage/BookFeedTab.tsx
  src/components/BookDetailPage/BookMyReview.tsx
  src/components/BookSearchPage/BestBookCard.tsx
  src/components/BookSearchPage/SearchBookCard.tsx
  src/components/BookShelvesPage/BookDetailDialog/BookDetailDialog.tsx
  src/components/FeedPage/PostCard/PostCardFooter.tsx
  src/components/FeedPage/PostTypeSelectDialog/PostTypeButton.tsx
  src/components/Header/Header.tsx
  src/components/Header/userMenu.tsx
  src/components/LoginSignupPage/Login/Login.tsx
  src/components/LoginSignupPage/Signup/Signup.tsx
  src/components/MyPage/Feed/OneLineReviewSection.tsx
  src/components/MyPage/Feed/PostingSection.tsx
  src/components/MyPage/FollowList.tsx
  src/components/MyPage/Library/BookshelfCard.tsx
  src/components/NotFoundPage/NotFoundContent.tsx
  src/components/PostingDetailPage/PostingHeader.tsx
  src/components/PostingWritePage/PostingWriteHeader.tsx
  src/components/ReviewMorePage/ReviewMorePageTemplate.tsx
  src/features/SNSLogin/auth/KakaoCallback.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/PasswordChkPage/PasswordChkPage.tsx
  src/routes/RoutePath.ts
  src/routes/index.tsx
  src/shared/utils/navigation.ts
  tsconfig.app.json
Labels: refactor

#258 사용자 인증 상태에 따른 리다이렉션
  src/App.tsx
  src/components/AdditionalInfo/AdditionalInfo.tsx
  src/hooks/useRequireAdditionalInfo.ts
Labels: bug, feature

#268 프로필 사진 업로드 시 이미지 압축
  package-lock.json
  package.json
  src/features/user/userApi.ts
Labels: feature

#275 페이지 공통 성능 개선
  src/App.tsx
  src/components/commons/NonTitleDialog.tsx
  src/pages/EditAccountPage/EditAccountPage.tsx
  src/routes/index.tsx
  vite.config.ts
Labels: perfomance

#274 Throttling 오류
  src/App.tsx
  src/components/AdditionalInfo/AdditionalInfo.tsx
  src/hooks/useRequireAdditionalInfo.ts
Labels: bug

#279 NonTitleDialog 오류 해결
  src/components/commons/NonTitleDialog.tsx
Labels: bug

#276 리드미 수정
  README.md
Labels: documentation

#277 리드미 파일 수정
  README.md
Labels: documentation
